- hosts: linux
  become: yes
  become_method: sudo
  remote_user: root
  tasks:
   - name: Transfer the script
     copy: src=ic.sh dest=/tmp/ic2.sh mode=0700

   - name: Execute the script
     command: bash /tmp/ic2.sh
